from sapp.controllers.student_controller import StudentController
from sapp.controllers.teacher_controller import TeacherController
from sapp.controllers.school_class_controller import SchoolClassController

