from sapp.repositories.student_repository import StudentRepository
from sapp.repositories.teacher_repository import TeacherRepository
from sapp.repositories.school_class_repository import SchoolClassRepository
from sapp.repositories.subject_repository import SubjectRepository
from sapp.repositories.group_repository import GroupRepository
from sapp.repositories.user_repository import UserRepository
from sapp.repositories.quiz_repository import QuizRepository, QuizQuestionRepository
from sapp.repositories.process_repository import ProcessRepository
from sapp.repositories.education_repository import EducationPlanRepository, EducationTopicRepository, \
    AchievementRepository
